### PR TITLE
[RFC] Upgrade Jedi

### PR DESCRIPTION
**Pull request by blueyed**
Upgrade Jedi to 0.12.1+ (current master).

Fixes https://github.com/zchee/deoplete-jedi/issues/156.

### CODE REVIEW

**Comment by blueyed** [comment]
Rebased, for anybody wanting to use this already.

**Comment by Shougo** [comment]
OK.  I will use it.

**Comment by blueyed** [comment]
See https://github.com/zchee/deoplete-jedi/pull/184 for a version that only uses Jedi, and allows for changing `g:deoplete#sources#jedi#python_path` on the fly.

**Comment by blueyed** [comment]
Closing in favor of #184.

**Comment by blueyed** [comment]
Let's use this as a first step maybe - I think #184 is too slow without the cache.

**Comment by Shougo** [comment]
OK.  Please rebase the branch.
I will merge it later.

**Comment by blueyed** [comment]
Please test it before at least (where you can update it yourself).

**Comment by blueyed** [comment]
(I am using deoplete and deoplete-jedi in manual mode currently / not enabled by default, so am not really testing/using this myself)

**Comment by Shougo** [comment]
I have tested it and it works.

**Comment by Shougo** [comment]
@blueyed Ping.  I want to merge the branch.

**Comment by blueyed** [comment]
@Shougo 
Go ahead then.

**Comment by Shougo** [comment]
Merged.

**Pull request merged**
