### PR TITLE
Exclude jedi for flake8

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
@zchee 
This is now ready to be merged! :)

**Comment by zchee** [comment]
@blueyed Ah! I have an additional question, Can I ask you?

At first, I have no Python experience. I wrote the only deoplete-sources(jedi, clang, go). So I don't know Python manners.
Next is main topic, flake8 settings seems to can write the `setup.cfg` file and automatically handle it(correct ?)
but this project is not python module, no needs the `setup.py`.

Move the flake8 setting to `setup.cfg` or not, which one is good manner?

**Comment by blueyed** [comment]
> Move the flake8 setting to setup.cfg or not, which one is good manner?

It is often done like this, because other tools also look there.
For now however, I'd say to keep it in its own config file.

`setup.py` is a bit different from `setup.cfg` is that regard.

**Comment by blueyed** [comment]
Y U NO MERGE? ;)

**Comment by zchee** [comment]
@blueyed Oh, I got sleeping...
merged.

**Pull request merged**
