### PR TITLE
fix a little miss of debug method

### PR DESCRIPTION
**Pull request by jjwt**

### CODE REVIEW

**Comment by tweekmonster** [comment]
@jjwt This is actually not an error.  Python's logging facility performs string interpolation using the arguments using `logging.Formatter`.  This allows logging filters and handlers can inspect the arguments before emitting the message.

You can read about it here: https://docs.python.org/3/library/logging.html#logging.debug

**Comment by jjwt** [comment]
@tweekmonster but how do you think @Shougo make it as a python logging instance?
to find it out , i use 2 commands below:
```bash
➜  ~ find ~/.config/nvim/bundle/deoplete.nvim -name "*.py" | xargs grep "debug" | wc -l
21
➜  ~ find ~/.config/nvim/bundle/deoplete.nvim -name "*.py" | xargs grep "logging" | wc -l
0
```
in fact, error message comes out befor i want to fix. here is the message:
```bash
[deoplete] Traceback (most recent call last):
[deoplete]   File "~/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 49, in completion_begin
[deoplete]     context)
[deoplete]   File "~/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 99, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "~/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 155, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "~/.config/nvim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
[deoplete]     return func(self, *args, **kwargs)
[deoplete]   File "~/.config/nvim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 140, in gather_candidates
[deoplete]     self.debug('Key: %r, Refresh: %r, Wait: %r', cache_key, refresh, wait)
[deoplete] TypeError: debug() takes 2 positional arguments but 5 were given
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "~/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 49, in completion_begin
[deoplete]     context)
[deoplete]   File "~/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 99, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "~/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 155, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "~/.config/nvim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
[deoplete]     return func(self, *args, **kwargs)
[deoplete]   File "~/.config/nvim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 140, in gather_candidates
[deoplete]     self.debug('Key: %r, Refresh: %r, Wait: %r', cache_key, refresh, wait)
[deoplete] TypeError: debug() takes 2 positional arguments but 5 were given
[deoplete] An error has occurred. Please execute :messages command.
```

**Comment by tweekmonster** [comment]
@jjwt are you using a recent version of deoplete.nvim?  The `Base` class inherits `LoggingMixin`: https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/logger.py#L80

**Comment by jjwt** [comment]
@tweekmonster sorry, i use :NeobundleCheckUpdate ,which does not update deoplete, and i have not find it util i use :NeobundleUpdate!, sorry for waste of your time.

**Comment by tweekmonster** [comment]
No problem!  `NeoBundleCheckUpdate` should update if there's a newer version.  Maybe neobundle is outdated too or has a bug?

**Comment by jjwt** [comment]
Maybe because I have not update all plugins for long, until I install the deoplete-jedi and come to the error.

**Pull request closed without merging**
