### PR TITLE
Updated README with cloning submodule note

### PR DESCRIPTION
**Pull request by tweekmonster**
Does this look fine?

Reference: #108

### CODE REVIEW

**Comment by blueyed** [comment]
There would be also `--recursive` for git-clone.

**Comment by tweekmonster** [comment]
@blueyed WDYT?

**Comment by zchee** [comment]
@tweekmonster @blueyed Merged. Thanks!!

**Comment by tweekmonster** [comment]
Whew, thanks @zchee.  The suspense of finding out whether or not this commit would pass CI tests was too intense.

**Comment by zchee** [comment]
@tweekmonster Ah, sorry, I'll take care....

**Pull request merged**
