### PR TITLE
Fix linting issues

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by zchee** [comment]
@blueyed Thanks, I'll check it :)

**Comment by blueyed** [comment]
@zchee 
I think we should ditch flake8-import-order - seems to be too strict.
(Or configure it)

**Comment by zchee** [comment]
@blueyed Ah, Hm
OK, could you also remove flake8-import-order module from requirement.txt?

**Comment by blueyed** [comment]
Oh, the remaining issues come from `hacking`:
```
rplugin/python3/deoplete/sources/deoplete_jedi.py:7:32: H301: one import per line
rplugin/python3/deoplete/sources/deoplete_jedi.py:9:6: H304: No relative imports. 'from .base import Base' is a relative import
rplugin/python3/deoplete/sources/deoplete_jedi/helper.py:2:36: H301: one import per line
rplugin/python3/deoplete/sources/deoplete_jedi/worker.py:7:6: H304: No relative imports. 'from .server import Client' is a relative import
rplugin/python3/deoplete/sources/deoplete_jedi/worker.py:8:6: H304: No relative imports. 'from .utils import file_mtime' is a relative import
rplugin/python3/deoplete/sources/deoplete_jedi/server.py:22:1: H306: imports not in alphabetical order (time, glob.glob)
rplugin/python3/deoplete/sources/deoplete_jedi/cache.py:10:1: H306: imports not in alphabetical order (time, itertools.chain)
rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py:17:7: H201: no 'except:' at least use 'except Exception:'
```

**Comment by zchee** [comment]
@blueyed Are you thinking also hacking too strict?

**Comment by blueyed** [comment]
Yes, some of those things are - and conflict with what `isort` provides.
I configured it.

**Comment by zchee** [comment]
@blueyed Thanks disable some rules.
LGTM.

**Comment by zchee** [comment]
@blueyed BTW, I never used `isort` use alone. (IIRC @tweekmonster also)
Where did the error come from?

**Comment by blueyed** [comment]
I don't know.  Maybe package updates again?!

I have those commands in my vimrc:
```vim
" Sort Python imports.
command! -range=% -nargs=* Isort :<line1>,<line2>! isort --lines 79 <args> -
command! -range=% -nargs=* Isortdiff :<line1>,<line2>w !isort --lines 79 --diff <args> -
```

The `--lines 79` could be removed - isort can be configured also through `setup.cfg`.

**Comment by zchee** [comment]
@blueyed Oh, Hm. I'll research it.

That's useful command. Thanks.
But I think already you know this plugin - I use [tweekmonster/impsort.vim](https://github.com/tweekmonster/impsort.vim) :D

Anyway, thanks PR!!

**Comment by tweekmonster** [comment]
I should've commented on this when I had a chance, but I don't like `isort`'s results ☹️

**Comment by zchee** [comment]
@blueyed @tweekmonster I'm not particular about Python formatting. (because I'm Python newbie :P)
Re-formatting import section, or not change, anything will be fine. I'll leave to you.

**Comment by blueyed** [comment]
@tweekmonster 
Sorry.
What is it that you do not like in particular?
There are different styles..

What about a config like
```
[isort]
known_first_party = deoplete_jedi
default_section = THIRDPARTY
lines = 79
multi_line_output = 5
include_trailing_comma = 1
order_by_type = 1
combine_as_imports = 1
force_sort_within_sections = 1
use_parentheses = 1
```

**Comment by blueyed** [comment]
That does not change much though:
```diff
diff --git c/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py i/rplugin/python3/deople
index 98018f8..9df8e20 100644
--- c/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py
+++ i/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py
@@ -1,14 +1,14 @@
 import glob
 import hashlib
+from itertools import chain
 import json
 import logging
 import os
 import re
+from string import whitespace
 import subprocess
 import threading
 import time
-from itertools import chain
-from string import whitespace
 
 from deoplete_jedi import utils
 
diff --git c/rplugin/python3/deoplete/sources/deoplete_jedi/server.py i/rplugin/python3/deopl
index b398f06..0f49591 100644
--- c/rplugin/python3/deoplete/sources/deoplete_jedi/server.py
+++ i/rplugin/python3/deoplete/sources/deoplete_jedi/server.py
@@ -12,6 +12,7 @@
 
 import argparse
 import functools
+from glob import glob
 import logging
 import os
 import re
@@ -19,7 +20,6 @@
 import subprocess
 import sys
 import time
-from glob import glob
 
 # This is be possible because the path is inserted in deoplete_jedi.py as well
 # as set in PYTHONPATH by the Client class.
```

**Comment by tweekmonster** [comment]
I liked it basically the way it was.  Grouping: builtin, thirdparty, local.  Sorting: length, alphabetic.  Secondary Grouping: by module, Sorting: module package length, alphabetic.  Each grouping separated by a blank line.

Explanation for my formatting preferences: I like being able to see that something's wrong by glancing at the shape of the code vs actually reading each line.  Plain alphabetic sorting makes the code look lumpy and disorganized.

I moved away from isort and made `impsort.vim` because I felt it was too rigid to get it to fit the shape I wanted.  In any case, I don't hate it *that* much.  I can cope with whatever can stay consistent between contributors.

**Comment by blueyed** [comment]
Have to look at import.vim.
Can it be used for checking also? (so that we can drop the flake8 plugin)
Or let us just drop the sort linter completely for now?

**Comment by tweekmonster** [comment]
Oh, I missed the part that this was in response to a linter.  😳

> Can it be used for checking also?

Not at the moment.  But, I think porting it to Python wouldn't be difficult.

> Or let us just drop the sort linter completely for now?

Yes.  I'm fine with having linters that just check for widely regarded "good style", and not so much for the more opinionated ones.  Due to the lack of block delimiters in Python, "good style" means writing code that makes it harder to make simple mistakes or inadvertently introduce "gotchas" when refactoring code.  I don't think the order of imports has the same implications as poorly placed line continuations.

A little off topic: I apologize for being, myself, very opinionated.  It sounds hypocritical for me to bemoan other opinionated Python coding styles.  I just feel that they go a little too far for the sake of covering everything.

**Pull request merged**
