### PR TITLE
Fix #170 path problem

### LINKED ISSUE #170: "Error when loading source jedi: Failed to start server" when using virtualenv at Windows
# Problem summary

Code completion work well on python files without virtualenv, but when virtualenv activated, deoplete hit error on noevim startup as below;

deoplete-jedi-virtualenv

The problem shall be due to the path it pointed to is contains front slash which is interpreted as command option in Windows.

invalid_parameters

## Expected

Code completion shall still work with virtualenv

## Environment Information

 * OS: Windows 10
 * Neovim version: 0.3.0
 * Python version: 3.6

## Provide a minimal init.vim with less than 50 lines (required)

```vim
let g:python3_host_prog=expand('$HOME/AppData/Local/nvim/python_env/neovim3/Scripts/python.exe')
let g:python_host_prog=expand('$HOME/AppData/Local/nvim/python_env/neovim/Scripts/python.exe')

call plug#begin('~/AppData/Local/nvim/plugged')
if has('nvim')
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
    Plug 'Shougo/deoplete.nvim'
    Plug 'roxma/nvim-yarp'
    Plug 'roxma/vim-hug-neovim-rpc'
endif 
Plug 'zchee/deoplete-jedi'

" Use deoplete.
let g:deoplete#enable_at_startup = 1
```

## Steps to reproduce the issue after starting Neovim (required)

 1. at command prompt, activate virtualenv : `env\Scripts\activate`
 2. open a python file: `nvim test.py`
 
## Screen shot (if possible)

deoplete-jedi-virtualenv
invalid_parameters

### PR DESCRIPTION
**Pull request by Shougo**

### CODE REVIEW

**Comment by Shougo** [comment]
@thiamteck Please test it.

**Comment by thiamteck** [comment]
Hi @Shougo, apparently the python program path is also different in Windows and Linux. Below is my additional changes that was tested working, start from line 475:

``` python
        if 'VIRTUAL_ENV' in os.environ:
            if os.name == 'nt':
                prog = os.path.join(self.env['VIRTUAL_ENV'], 'Scripts', 'python')
            else:
                prog = os.path.join(self.env['VIRTUAL_ENV'], 'bin', 'python')
        elif python_path:
            prog = python_path
        else:
            prog = 'python'

        self.cmd = [prog, '-u', os.path.normpath(__file__),
                    '--desc-length', str(desc_len)]
```


complete file at: 
https://gist.github.com/thiamteck/9e9a0eac1aa27c021af8f4d395cfd1a9 

Thank you.

**Comment by davidhalter** [comment]
@Shougo This is not how you should be starting Jedi. Jedi already creates a subprocess for you and does `$VIRTUALENV` handling  with 0.12.0.

**Comment by Shougo** [comment]
I know jedi 0.12.0 already supports it.
But deoplete-jedi does not support jedi 0.12.0 yet.

**Comment by davidhalter** [comment]
Ah ok. May I ask why?

**Comment by Shougo** [comment]
Because....

https://github.com/zchee/deoplete-jedi/pull/172

**Pull request merged**
