### PR TITLE
Update Jedi to 0.10.2

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by zchee** [comment]
@blueyed Thanks. I'll try test it.

**Comment by zchee** [comment]
@blueyed Hm, some completion are not displayed. I'll debug it.

**Comment by zchee** [comment]
@Shougo also, If you have time, please test it. Thanks.

**Comment by blueyed** [comment]
@zchee 
Shouldn't the cache be handled automatically, e.g. based on Jedi's version?

**Comment by zchee** [comment]
@blueyed Sorry, what means you said?
I was just deleted only deoplete-jedi's server cache `$XDG_CACHE_HOME/deoplete/jedi/3.5 ~ 3.6`. similar https://github.com/zchee/deoplete-jedi/issues/93#issuecomment-278539429.
After that, try new version Jedi submodule, but some modules does not completion.

Like, `os.|...` is OK, but `re.|...` is not completion. so I'm confused. I'll debug it.

**Comment by blueyed** [comment]
@zchee 
I mean that deoplete-jedi should invalidate the cache automatically.

**Comment by zchee** [comment]
@blueyed Oh, wait.
It means, We should add disable or clear (before) server cache command, or automatically clear the cache on server side?
If so, totally agree and I thought it, too.

**Comment by tweekmonster** [comment]
> We should add disable or clear (before) server cache

Bump this version: https://github.com/zchee/deoplete-jedi/blob/6240de812f06263524f46379ad08a0d3d539730f/rplugin/python3/deoplete/sources/deoplete_jedi/cache.py#L22

**Comment by zchee** [comment]
@tweekmonster Ah, maybe figure out.
If that variable to increase, the server is automatically clear cache, right?
If so, just `++` this line after the merged this pull request.

**Comment by blueyed** [comment]
I've amended the commit to bump the cache version.

**Comment by tweekmonster** [comment]
> If that variable to increase, the server is automatically clear cache, right?

It doesn't *clear* the cache.  It ignores the cached files if the version in the file is lower than the current version.  It's a passive way to invalidate old cache formats.  So, if the JSON cache structure needs to change, that version should increase.

It might be good to add a command to manually clear the cache, though.

Anyway, this PR LGTM!

**Comment by blueyed** [comment]
btw: jedi-vim has a `JediClearCache` command, too (https://github.com/davidhalter/jedi-vim/blob/master/autoload/jedi.vim#L298-L303).

**Comment by tweekmonster** [comment]
Jedi's filesystem cache is disabled because it seemed like it wasn't reusing the disk cache after a reload.  The default cache time was very short, too.  AFAICT, even with the cache, it still recursed into modules so it didn't seem like it was making things much faster.  Maybe it's improved a lot since 0.8.0?

Also, do you think clearing the cache would fix the issue with Jedi progressively getting slower?  Because we could stop auto-restarting the server if that's resolved.

**Comment by zchee** [comment]
@blueyed @tweekmonster Wait, back to the original topic.
Could you get completion with upgrade jedi submodule? I was quick tested, but some modules can't get a completion.
Maybe I'm wrong?

**Comment by blueyed** [comment]
I could confirm that completions for `re.` did not work first - the cache file `~/.cache/deoplete/jedi/3.6/re.json` was empty then:
```
{"completions": [], "modules": {}, "version": 11, "cache_key": ["re", "package"], "time": 1486941366.54822}
```
(ignore the version, I've reverted this PR/change and tried to bisect it in Jedi)

But then it started to work also with Jedi master (used in this PR, 3ac1427).

So it might be something hard to reproduce?!

**Comment by zchee** [comment]
@blueyed Yep, I was the same result.
I'll trying the debug it later.

**Comment by zchee** [comment]
@blueyed @tweekmonster 
Now I'm struggling to flatbuffers and libclang for next-gen deoplete-clang 😫   So sorry, I do not debug it yet...
Do you found the causes that the empty of json cache?

**Comment by arkottke** [comment]
What's the status of this?

**Comment by blueyed** [comment]
@arkottke 
Read the previous comments: there are some issues we ran into when testing it, and @zchee seems to not find the time to debug it as promised (which is find).
Have you tried it yourself?
Your input might help here then.

**Comment by zchee** [comment]
@tweekmonster @blueyed Now, I just tried `git submodule update --init --remote`(fetch latest), but same result. json cache file always empty.
I don't know yet why it happened but jedi changed some API...?

**Comment by zhou13** [comment]
Current jedi has serious bug:

````
a = 'import numpy as np\nnp.\n\n\nif __name__ == "__main__":\n    a = 0\n    b = 9\n    d = a + b\n    c = d\n    print(c, d)'
>>> jedi.Script(a, 2, 3, "/tmp/1.py").completions()
[<Completion: abs>, <Completion: absolute_import>, <Completion: add_newdocs>, <Completion: bench>, <Completion: bool>, <Completion: compat>, <Completion: com
plex>, <Completion: core>, <Completion: ctypeslib>, <Completion: distutils>, <Completion: division>, <Completion: doc>, <Completion: dual>, <Completion: f2py
>, <Completion: fft>, <Completion: float>, <Completion: int>, <Completion: lib>, <Completion: linalg>, <Completion: long>, <Completion: ma>, <Completion: mat
lib>, <Completion: matrixlib>, <Completion: max>, <Completion: min>, <Completion: ModuleDeprecationWarning>, <Completion: msg>, <Completion: numarray>, <Comp
letion: object>, <Completion: oldnumeric>, <Completion: PackageLoader>, <Completion: pkgload>, <Completion: polynomial>, <Completion: print_function>, <Compl
etion: random>, <Completion: round>, <Completion: setup>, <Completion: show_config>, <Completion: str>, <Completion: sys>, <Completion: test>, <Completion: T
ester>, <Completion: testing>, <Completion: unicode>, <Completion: version>, <Completion: VisibleDeprecationWarning>, <Completion: warnings>, <Completion: _d
istributor_init>, <Completion: _globals>, <Completion: _import_tools>, <Completion: _mat>, <Completion: _NoValue>, <Completion: __all__>, <Completion: __conf
ig__>, <Completion: __doc__>, <Completion: __file__>, <Completion: __git_revision__>, <Completion: __name__>, <Completion: __NUMPY_SETUP__>, <Completion: __p
ackage__>, <Completion: __version__>]
````

This causes #93.

**Comment by blueyed** [comment]
Updated for Jedi 0.10.2.

**Comment by zchee** [comment]
please self merge because I'm in hospital

**Comment by blueyed** [comment]
@zchee 
I hope you're OK and get well soon!

**Comment by zchee** [comment]
@bkueyed Thanks :)

**Pull request merged**
