### PR TITLE
update jedi

### PR DESCRIPTION
**Pull request by meiralins**
After updating to Python3.6 I had the same problem as #98.
Just updating the jedi submodule solved it for me.

### CODE REVIEW

**Comment by Shougo** [comment]
@zchee We should update jedi.

**Comment by blueyed** [comment]
@meiralins 
Are you using jedi's dev or master branch?

The update was rejected for jedi-vim still a few days ago: https://github.com/davidhalter/jedi-vim/pull/650.

**Comment by Shougo** [comment]
@blueyed jedi-vim has already supported Python3.6?

**Comment by tweekmonster** [comment]
> jedi-vim has already supported Python3.6?

No.  The Jedi update was rejected because 3.6 isn't fully supported yet.

@blueyed I haven't had a need to try 3.6 yet, but would it still be broken for deoplete-jedi even if 3.6 support is incomplete in jedi?

**Comment by Shougo** [comment]
Hm.....
But Python 3.6 is released and ArchLinux is already Python 3.6.
We should fix the problem as possible.

**Comment by Shougo** [comment]
I use ManjaroLinux.  It is ArchLinux based distribution.
It uses Python3.5.2 but it will be updated to Python3.6 soon.
So Python3.6 support is important for me.

**Comment by tweekmonster** [comment]
@Shougo Yes, but the update may not change anything if Jedi is still broken.  AFAIK, only the 3.6 syntax file was added, but Jedi doesn't support all the new features.  But...it might work fine as long as the scripts being edited don't use any 3.6 features.

@meiralins Can you confirm this?  If 3.6 features in an edited script is still producing errors, but deoplete-jedi will work correctly when editing scripts *without* 3.6 features while using the python3.6 interpreter, I would be fine with accepting this PR as long as there's a note in the README or docs mentioning this caveat.

**Comment by Shougo** [comment]
> @Shougo Yes, but the update may not change anything if Jedi is still broken. AFAIK, only the 3.6 syntax file was added, but Jedi doesn't support all the new features. But...it might work fine as long as the scripts being edited don't use any 3.6 features.

Yes, I think it just hack until Python3.6 is supported in jedi.
But the hack is needed currently.

**Comment by meiralins** [comment]
Confirming: deoplete-jedi doesn't work at all when running in a python3.6 environment.
just updating jedi fixed for me. I just pulled from master and things seem to work ok for now.

This hack fixes for now, and I agree its not ideal.

One thing that could also fix for now, is to use the jedi submodule only as a fallback if its not installed.

**Comment by meiralins** [comment]
I forgot to mension that nvim/python-client is currently broken for python3.6.
I made a [PR](https://github.com/neovim/python-client/pull/241) to fix that, and I'm running on that branch.

Lols. I think I should have just created an issue instead of this PR.

**Comment by tweekmonster** [comment]
> Lols. I think I should have just created an issue instead of this PR.

@meiralins Nah, deoplete-jedi can work as a completer for a version other than what's used to run `python-client` (as you already know).

I think you misunderstood my confirmation request: Does deoplete-jedi still gives completions when using 3.6 (e.g. as a virtualenv) with the updated submodule in this PR when editing a script that has no 3.6-specific features like the `f""` literals mentioned in davidhalter/jedi-vim#650 ?

The idea is that we could still accept this and squash the error for people using 3.6 "just to have the latest" or if their work uses modules that require 3.6, but their code doesn't actually use 3.6 features.

I could confirm it myself, but I'm afraid I might cleverly sidestep any real issues because of how well I know this plugin and how off da hook my python setup is.  😎

**Comment by blueyed** [comment]
I think we should just merge this for now already: Jedi (also in jedi-vim) just bails out with Python 3.6.
Providing feedback here would be a new issue.. but the errors are only on stderr with vim-jedi also (IIRC).
There have been additional fixes to improve this (fallback) in the Jedi "dev" branch (IIRC), but I think it's good to use `master` here.

**Comment by blueyed** [comment]
> Does deoplete-jedi still gives completions when using 3.6 (e.g. as a virtualenv) with the updated submodule in this PR when editing a script that has no 3.6-specific features like the f"" literals mentioned in davidhalter/jedi-vim#650 ?

Yes.

**Comment by blueyed** [comment]
@tweekmonster 
> squash the error

What should we squash?!
Jedi appears to fail hardly..
As said before, we should rather not swallow that error, but display it (once - on init?!).

**Comment by blueyed** [comment]
You have 14 minutes before I'll merge this..

**Comment by tweekmonster** [comment]
> You have 14 minutes before I'll merge this..

Haha, I was hovering over the "merge" button until you commented.  Feel free to merge.  I'm fine with this since it technically doesn't break deoplete-jedi itself.

> What should we squash?!

The error about the python3.6 grammar not existing!

**Comment by tweekmonster** [comment]
Also I lied about my python setup being off da hook.  I didn't want to test/confirm because I'm not 100% lucid since I'm just now getting better after being sick all weekend.

**Comment by blueyed** [comment]
>> What should we squash?!

> The error about the python3.6 grammar not existing!

Ah.  And you've meant to display it, or just fail silently over and over again there?!
I think what should have happened is that py3.6 users would have seen an error once, and then we would have just disabled ourselves.

**Comment by blueyed** [comment]
@tweekmonster 
> Also I lied about my python setup being off da hook. I didn't want to test/confirm because I'm not 100% lucid since I'm just now getting better after being sick all weekend.

Heh.  I assume your Python setup to still being off da hook though.. 😆 

As for me: I did not do the Arch py36 upgrade yet, but have tested in `pyenv` virtualenvs - which got complicated by the fact that first my vimrc sets `g:python3_host_prog` to the system's Python forcefully (to avoid `pyenv which` etc), and then I managed to remove `deoplete-jedi` from my loaded plugins accidentally yesterday.

**Comment by blueyed** [comment]
@meiralins 
Thanks!
Also for the other issues you've created!

**Comment by tweekmonster** [comment]
Well, Jedi shouldn't emit an error about the 3.6 grammar not existing any more by default.  I think a one-time warning should be emitted stating that 3.6 is not fully supported yet.  The server should still eat the errors and log them since it's important for it to keep running.

**Comment by blueyed** [comment]
> Well, Jedi shouldn't emit an error about the 3.6 grammar not existing any more by default.

That is fixed now, and improved in Jedi's `dev` branch.

> I think a one-time warning should be emitted stating that 3.6 is not fully supported yet.

Yeah, a one-time warning (actually an error) should be emitted: it should be some good error for exceptions we recognize, or otherwise the exception (with traceback).

> The server should still eat the errors and log them since it's important for it to keep running.

Well, in this case (an exception we (would) recognize) we would know that Jedi just fails always afterwards, and therefore we should rather disable ourselves, no?

**Comment by tweekmonster** [comment]
> That is fixed now, and improved in Jedi's dev branch.

Oh, I think we're a bit mixed up.  I'm referring to the error that was discussed in #69 which will no longer be an issue because of this PR.  That's the error I want this PR to "squash" at the very least.

> actually an error

Completions could still work if no 3.6 features are used.  I think a warning (e.g. it works, *but...*) is more appropriate.  An error would imply that the user or the plugin is at fault for unexpected behavior and might generate issues on GH.  Also, deoplete will disable a source if it emits 3 consecutive errors, which we should avoid for a known issue.

> Well, in this case (an exception we (would) recognize) we would know that Jedi just fails always afterwards, and therefore we should rather disable ourselves, no?

Yeah, but the thing is, I'm not sure what exception Jedi would raise.  If it's the generic SyntaxError, there would be no way for us to know if it was user error or if it was because of Jedi + 3.6.

**Comment by blueyed** [comment]
I think the main issue is that Jedi just bails out when being used on py35+!

**Comment by zchee** [comment]
@meiralins and all
Thanks for merge it. I'm 😷  a little.
sorry for delay reply.

**Pull request merged**
