### PR TITLE
Correct caching of import lines

### PR DESCRIPTION
**Pull request by tweekmonster**
- Beginning import lines display modules only
- Improved cacheable key detection

### CODE REVIEW

**Comment by tweekmonster** [comment]
Sorry about making a new PR so soon regarding the cache.  I noticed that import lines were incorrectly using the wrong cache.  I also fixed it so that lines such as `if os.` would correctly use the cache.

**Comment by zchee** [comment]
@tweekmonster Thanks :)

> Sorry about making a new PR so soon regarding the cache.

NP, I also noticed the wrong cache.

But sorry, I want a little bit of time to understand this code :sweat:
Please wait a moment.

**Comment by tweekmonster** [comment]
> But sorry, I want a little bit of time to understand this code :sweat:

Np!  I'm in no rush because I'm already using the fixed plugin :stuck_out_tongue_winking_eye:

**Comment by zchee** [comment]
@tweekmonster I was poor physical condition yesterday.
I will check today.

> Np! I'm in no rush because I'm already using the fixed plugin :stuck_out_tongue_winking_eye:

Thanks :)

**Comment by tweekmonster** [comment]
@zchee I hope it was nothing serious!  Get well before worrying about this.

**Comment by zchee** [comment]
@tweekmonster I checked.
LGTM.

> I hope it was nothing serious! Get well before worrying about this.

Thanks :)

**Pull request merged**
