### PR TITLE
Try script completions before falling back other methods

### LINKED ISSUE #89: deoplete-jedi doesn't show all completion candidates that jedi-vim can
# Problem summary
This issue needs a confirmation. Because i'm not sure is it something with my config or deoplete-jedi problem itself.
There is no candidates for something like django's `admin.site. ....`
or deoplete-jedi doesn't show candidates for statements inside django's classes, etc.
```
class BookAdmin(admin.ModelAdmin):
    list_display
```

## Expected
jedi-vim candidates 

 * Neovim version:
0.1.6

### PR DESCRIPTION
**Pull request by tweekmonster**
Fixes #89

@monkoose could you try this branch and see if it works for you?

ping @blueyed @Shougo

### CODE REVIEW

**Comment by zchee** [comment]
@tweekmonster Thanks. 
@blueyed Also thanks for double checking.

I'm never used django, so I do not know if my check is correct.
But LGTM. Waiting for @monkoose reply.

**Comment by monkoose** [comment]
Will try in 30 min

**Comment by zchee** [comment]
@tweekmonster Oh, thanks rebase master but included `Merge branch 'master' into fix-89` message.
Is that missing `git rebase`?

**Comment by monkoose** [comment]
Seems like 0321e22 is working for me. Atleast the problems i described in #89 issue. Now there is candidates for admin.site. and classes statement etc. But @blueyed next commits is breaking deoplete-jedi for me at all with alot of errors. So i stay with 0321e22 for now

Thank you @tweekmonster You are not tweek you are TWEAKmonster:) It's like third time you helped me.

**Comment by zchee** [comment]
@monkoose Thanks test.
That's problem maybe caused by module import order.
https://github.com/zchee/deoplete-jedi/commit/9830e704ca5e28df1a6c3da1a01392df0fa10d93#commitcomment-20036506
/cc @blueyed

**Comment by zchee** [comment]
@monkoose Could you re-try with rebase it?
https://github.com/zchee/deoplete-jedi/pull/92

**Comment by monkoose** [comment]
@zchee one moment please.

**Comment by monkoose** [comment]
No errors this time, so i think its working.
Just do not forget to about 0321e22

**Comment by zchee** [comment]
@monkoose Thanks and got it.
@tweekmonster Sorry, please rebase #92.

**Comment by blueyed** [comment]
@zchee 
> Is that missing git rebase?

I merged master through the GitHub UI (twice now) - we should just squash it when merging.

**Comment by zchee** [comment]
@blueyed Ohh, I see. Yes, should squash.
As I said before, I've never used django(or some large module). and now @tweekmonster is not on-time?
So, if you think no problem this pull request, please merge it.

**Comment by tweekmonster** [comment]
The issue was due to jedi's shortcomings at the time.  deoplete-jedi's old completion method was better because it took less time and dealt with broken scopes that jedi used to crash on.  It looks like jedi's parsing has improved.

> Thank you @tweekmonster You are not tweek you are TWEAKmonster:) It's like third time you helped me.

😻

**Pull request merged**
