### PR TITLE
Kill server if it takes too long on a task

### PR DESCRIPTION
**Pull request by tweekmonster**
Partial fix for #58 

Not sure if 10 seconds is too long or too short for this.

### CODE REVIEW

**Comment by zchee** [comment]
@tweekmonster Sorry for late reply. I caught a terrible cold.
I'll check later, or feel free to self merge it.

**Comment by tweekmonster** [comment]
@zchee np!  I'll wait for a review since this is a non-trivial change.

**Comment by zchee** [comment]
@tweekmonster Thanks :D
I'm feeling a little better today. So I'll check it and will merge.

**Comment by zchee** [comment]
@blueyed Thanks, I'll merge it tonight.

**Comment by zchee** [comment]
@tweekmonster @blueyed Thanks and sorry for late.
Merged.

**Pull request merged**
