### PR TITLE
vendor: update jedi to 2ba78ab

### PR DESCRIPTION
**Pull request by zchee**
updtae jedi to https://github.com/davidhalter/jedi/commit/2ba78ab725f1e02dfef8bc50b0204cf656e8ee23

### CODE REVIEW

**Comment by blueyed** [comment]
Heh, we did the same for jedi-vim today also: https://github.com/davidhalter/jedi-vim/pull/635

**Comment by zchee** [comment]
@blueyed I did PR because I saw it lol

**Comment by zchee** [comment]
Now fixed CI fail on another branch...

**Comment by zchee** [comment]
@tweekmonster @blueyed Passes CI test.
I'll merge.

**Pull request merged**
