### PR TITLE
Better handling of server startup errors

### PR DESCRIPTION
**Pull request by blueyed**
This uses deoplete.exceptions.SourceInitError, proposed in
https://github.com/Shougo/deoplete.nvim/pull/417.

### CODE REVIEW

**Comment by Shougo** [comment]
Pending until Shougo/deoplete.nvim#417 is merged.

**Comment by blueyed** [comment]
Shougo/deoplete.nvim#417 has been merged.

**Comment by zchee** [comment]
@blueyed LGTM, thanks.

**Comment by zchee** [comment]
I'll merge it. thanks!

**Pull request merged**
