### PR TITLE
Add g:deoplete#sources#jedi#ignore_errors

### PR DESCRIPTION
**Pull request by Shougo**

### CODE REVIEW

**Comment by blueyed** [comment]
Hmm, what is your use case?
I do not like errors being silent in general, but at least this is opt-in.

**Comment by Shougo** [comment]
I get some jedi errors when use deoplete-jedi.
I want to disable them.

**Comment by Shougo** [comment]
Jedi should be more stable though.

**Comment by blueyed** [comment]
> I get some jedi errors when use deoplete-jedi.

How about reporting/fixing them?

And what about disabling the source?  (if you get errors all the time)

**Comment by Shougo** [comment]
> How about reporting/fixing them?

It is already reported.  Example: https://github.com/davidhalter/jedi/issues/1253.

> And what about disabling the source? (if you get errors all the time)

Of course, the feature is already implemented in deoplete.
But I want to use jedi completion if possible.

**Pull request merged**
