### PR TITLE
[WIP] server: use deoplete.logger.log_format

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by Shougo** [comment]
The branch is out of date.

**Comment by blueyed** [comment]
Should get squash-merged.

**Comment by blueyed** [comment]
Not urgent, will take a look again myself.

**Comment by Shougo** [comment]
OK.

**Comment by blueyed** [comment]
The main topic of this PR was merged in https://github.com/zchee/deoplete-jedi/pull/161.

**Pull request closed without merging**
