### PR TITLE
README: clarify python_path

### PR DESCRIPTION
**Pull request by blueyed**
@Shougo 
Is it possible to default to `g:python3_host_prog` here?
Otherwise we could add an example to set it to it.

### CODE REVIEW

**Comment by Shougo** [comment]
Please rebase it.

**Comment by blueyed** [comment]
Why?
It is a bit ridiculous to have this out-of-date checks.
Are you able to override it when it is not up-to-date, i.e. are you admin?
/cc @zchee

**Comment by Shougo** [comment]
I'm just contributor.
Not admin...

**Comment by Shougo** [comment]
I cannot change the project settings.

**Comment by Shougo** [comment]
Merged.

**Pull request merged**
